[build]
  publish   = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
